---
- hosts: localhost
  roles:
    - httpd-proxy

#- hosts: vault
#  roles:
#    - vault

- hosts: vault
  vars:
    unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
    root_token_dir_output: "{{ playbook_dir }}/rootKey"
  roles:
    - vault
    - vault-init
    - vault-unseal
    - vault-ssh-engine-add
    - vault-ssh-add-role

- hosts: localhost
  roles:
    - base-init
    - google-pam
    - fail2ban-init
    - user-add

- hosts: vault
  roles:
    - user-copy-keys
