- name: Add epel repo
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  become: yes

- name: Install google-authenticator
  yum:
    name: "google-authenticator-{{ google_pam_version }}"
    state: present
  become: yes

- name: Add auth pam setting to /etc/pam.d/sshd
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '.*pam_google_authenticator.so'
    line: auth       required     pam_google_authenticator.so nullok
  become: yes

- name: Comment auth substack setting to /etc/pam.d/sshd
  lineinfile:
    dest: /etc/pam.d/sshd
    regexp: '^auth\s+substack\s+password-auth'
    line: #auth       substack     password-auth
  become: yes

- name: Add AuthenticationMethods for pam TOTP to sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^AuthenticationMethods'
    line: AuthenticationMethods publickey,keyboard-interactive
  become: yes

- name: Configure ChallengeResponseAuth for sshd_config
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^ChallengeResponseAuthentication'
    line: ChallengeResponseAuthentication yes
  become: yes
  notify: sshd_reload
