- name: Create user accounts and create ssh keys
  user:
    name: "{{ item }}"
    generate_ssh_key: true
  with_items: "{{ users }}"

- name: Sign certificate for user accounts
  uri:
    url: http://{{ vault_addr }}:{{ vault_port }}/v1/{{ vault_ssh_engine }}/sign/{{ vault_role }}
    method: POST
    body: {"public_key": "{{ lookup('file', '/home/{{ item }}/.ssh/id_rsa.pub') }}"}
    body_format: json
    headers:
      Content-Type: application/json
      X-Vault-Token: "{{ lookup('file', '{{ vault_token_dir }}') }}"
    return_content: yes
  register: json_response
  with_items: "{{ users }}"

- name: Copy signed certificate
  copy:
    content: "{{ item.json.data.signed_key }}"
    dest: /home/{{ item }}/.ssh/id_rsa-cert.pub
  with_items: "{{ json_response.results }}"
