- name: Install latest epel-release
  yum:
    name: epel-release
    state: latest
  become: yes

- name: Install fail2ban
  yum:
    name: fail2ban
    state: latest
  become: yes
  notify: fail2ban_reload
