- name: Creating vault user group
  group:
    name: "{{ vault_group }}"
  become: yes

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: /sbin/nologin
    comment: vault nologin User
    createhome: no
    state: present
  become: yes

- name: Vault dir for signed certs
  file:
    path: /vault/ca-user-signed
    state: directory
  become: yes

- name: Vault dir for pam secrets
  file:
    path: /vault/pam
    state: directory
  become: yes

- name: Configure yum proxy
  lineinfile:
    dest: /etc/yum.conf
    regexp: '^proxy='
    line: "proxy=http://{{ yum_proxy_addr }}:{{ yum_proxy_port }}"
  become: yes

- name: Install prerequisites
  package:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ vault_install_prerequisites }}"
  become: yes

- name: Download binary
  get_url:
    url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
    checksum: "{{ vault_checksum }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755
  environment:
    http_proxy: "http://{{ yum_proxy_addr }}:{{ yum_proxy_port }}"
    https_proxy: "http://{{ yum_proxy_addr }}:{{ yum_proxy_port }}"
  register: vault_download

- name: Unzip vault archive
  unarchive:
    src: "{{ vault_download.dest }}"
    dest: /usr/local/bin
    copy: no
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: 0755

- name: Set vault binary capabilities
  capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present
  become: yes

- name: config file
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
  become: yes

- name: Copy systemd init file
  template:
    src: init.vault.sysvinit.j2
    dest: /etc/init.d/vault
    owner: root
    group: root
    mode: 0755
#  notify: vault_reload
  become: yes

#- name: vault service
#  sysvinit:
#    name: vault
#    state: started
#    enabled: yes
#    runlevels:
#     - 2
#     - 3
#     - 4
#     - 5
#  become_method: sudo

#- name: vault ser
#  shell: "sudo /etc/init.d/vault restart"
#  become: yes

- name: enable sysv
  service:
    name: vault
    enabled: yes

- name: vault service
#  environment:
#    VAULT_ADDR: http://127.0.0.1:8200
  service:
    name: vault
    state: started
    pattern: "vault"
  become: yes

- name: sleep
  wait_for: timeout=10
  delegate_to: localhost
