- name: Install httpd
  yum:
    name: "httpd-{{ httpd_version }}"
    state: present
  become: yes

- name: Update binding address for httpd config
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^Listen'
    line: "Listen {{ proxy_addr }}:{{ proxy_port }}"
  become: yes

- name: Update ServerName for httpd config
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^#ServerName'
    line: "ServerName {{ proxy_addr }}:{{ proxy_port }}"
  become: yes

- name: Update ProxyRequests for httpd config
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^#ProxyRequests'
    line: ProxyRequests On
  become: yes

- name: Update ProxyVia for httpd config
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: '^#ProxyVia'
    line: ProxyVia On
  become: yes
  notify: httpd_reload
